use bitcode::{Decode, Encode};
use serde::{Deserialize, Serialize};

use crate::{
    beacon::BeaconCache,
    blockchain::{
        block::{Block, genesis_block},
        validation::is_valid_new_block,
    },
};

// For blocks older than CHECKPOINT_DEPTH, temperature verification is omitted.
pub const CHECKPOINT_DEPTH: usize = 600;

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize, Encode, Decode)]
pub struct Chain {
    pub blocks: Vec<Block>,
}

impl Default for Chain {
    fn default() -> Self {
        Self::new()
    }
}

impl Chain {
    pub fn new() -> Self {
        Self {
            blocks: vec![genesis_block()],
        }
    }

    pub fn get_latest_block(&self) -> Block {
        match self.blocks.last() {
            Some(block) => block.clone(),
            None => genesis_block(),
        }
    }

    pub fn replace(&mut self, new_chain: Chain, cache: &dyn BeaconCache, vdf_difficulty: u64) {
        if new_chain.is_valid(cache, vdf_difficulty) && new_chain.blocks.len() > self.blocks.len() {
            self.blocks = new_chain.blocks;
        }
    }

    pub fn get_block_depth(&self, block: &Block) -> usize {
        self.blocks
            .iter()
            .rev()
            .take_while(|b| b.hash != block.previous_hash)
            .count()
    }

    fn add_block_without_validation(&mut self, block: Block) {
        self.blocks.push(block);
    }

    /* Since blocks generated by the local node do not require beacon verification, the cache argument is passed as None. */
    pub fn add_block(
        &mut self,
        block: Block,
        cache: Option<&dyn BeaconCache>,
        vdf_difficulty: u64,
    ) -> bool {
        let previous_block = self.get_latest_block();
        let is_valid_new_block = is_valid_new_block(
            &block,
            &previous_block,
            &self.get_unspent_transactions().0,
            self.get_block_depth(&block),
            cache,
            vdf_difficulty,
        );

        if is_valid_new_block {
            self.add_block_without_validation(block);
        }
        is_valid_new_block
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::beacon::{Beacon, InMemoryBeaconCache};
    use crate::blockchain::block::{Block, genesis_block};
    use crate::blockchain::transaction::Transaction;
    use crate::util::signature::SignatureWrapper;

    fn dummy_block(prev: &Block, txs: Vec<Transaction>, beacon: i32) -> Block {
        Block {
            index: prev.index + 1,
            timestamp: prev.timestamp + 1,
            transactions: txs,
            beacon: Beacon {
                values: vec![beacon],
            },
            vdf_solution: vec![],
            previous_hash: prev.hash,
            issuer: prev.issuer.clone(),
            signature: SignatureWrapper::default(),
            hash: [prev.index as u8 + 1; 32],
        }
    }

    const TEST_VDF_DIFFICULTY: u64 = 10;

    #[test]
    fn new_has_only_genesis() {
        let c = Chain::new();
        assert_eq!(c.blocks.len(), 1);
        assert_eq!(c.get_latest_block(), genesis_block());
    }

    #[test]
    fn add_block_rejects_invalid_block() {
        let mut c = Chain::new();
        let bad = dummy_block(&c.get_latest_block(), vec![], 1);
        let cache = InMemoryBeaconCache::new();
        let changed = c.add_block(bad, Some(&cache), TEST_VDF_DIFFICULTY);
        assert!(!changed);
        assert_eq!(c, Chain::new());
    }

    #[test]
    fn replace_rejects_invalid_longer_chain() {
        let mut base = Chain::new();
        let g = genesis_block();
        let longer_but_invalid = Chain {
            blocks: vec![g.clone(), dummy_block(&g, vec![], 1)],
        };
        let cache = InMemoryBeaconCache::new();
        base.replace(longer_but_invalid, &cache, TEST_VDF_DIFFICULTY);
        assert_eq!(base, Chain::new());
    }

    #[test]
    fn get_block_depth_counts_from_tip() {
        let g = genesis_block();
        let b1 = dummy_block(&g, vec![], 1);
        let b2 = dummy_block(&b1, vec![], 2);
        let b3 = dummy_block(&b2, vec![], 3);
        let c = Chain {
            blocks: vec![g.clone(), b1.clone(), b2.clone(), b3.clone()],
        };

        assert_eq!(c.get_block_depth(&b3), 1);
        assert_eq!(c.get_block_depth(&b2), 2);
        assert_eq!(c.get_block_depth(&b1), 3);
        assert_eq!(c.get_block_depth(&g), 4);
    }
}
